<?php

namespace DataSourceBundle\Repository;

/**
 * DatasourcesDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatasourcesDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
