<?php

namespace CubesBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * CubesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CubesRepository extends \Doctrine\ORM\EntityRepository
{
}
