<?php

namespace DataSourceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DatasourceDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatasourceDetailRepository extends EntityRepository
{
}
