dashboard:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /t-admin

cubes:
    resource: "@CubesBundle/Controller/"
    type:     annotation
    prefix:   /t-admin

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /t-admin

sample:
    resource: "@SampleBundle/Controller/"
    type:     annotation
    prefix:   /

data_source:
    resource: "@DataSourceBundle/Controller/"
    type:     annotation
    prefix:   /t-admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"   