<?php

namespace AdminBundle\Repository;


/**
 * EntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
