<?php

namespace DashboardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DashboardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DashboardRepository extends \Doctrine\ORM\EntityRepository
{
}
